#!/bin/bash

# SPDX-License-Identifier: MIT
# X-SPDX-Copyright-Text: Copyright (C) 2022, Advanced Micro Devices, Inc.

LD_LIBRARY_PATH=/home/as/projects/solar_capture/src /home/as/projects/solar_capture/tests/four_threadsc $*
