/*
** SPDX-License-Identifier: MIT
** X-SPDX-Copyright-Text: Copyright (C) 2022, Advanced Micro Devices, Inc.
*/

/**
 * \node{sc_arista_ts}
 *
 * \brief Replace SolarCapture timestamp with timestamp from an Arista switch.
 *
 * \nodedetails
 * This node is used with new Arista switches that are configured to add
 * hardware timestamps to packets.  It replaces the SolarCapture timestamp
 * with the timestamp generated by the switch.  The node has several modes
 * for decoding timestamps from different models of arista switches and
 * different settings of timestamping on Arista switches.
 * The node arguments and statistics depend on the value of the switch_model
 * and ts_format arguments.
 *
 * \nodeargs
 * Argument         | Optional? | Default | Type           | Description
 * ---------------- | --------- | ------- | -------------- | --------------------------------------------------------------------------------------------------------------------------------
 * switch_model     | Yes       | NULL    | ::SC_PARAM_STR | Which switch timestamp protocol to decode.  Will assume "7150" if unspecified.
 * ts_format        | Yes       | NULL    | ::SC_PARAM_STR | Which timestamp format to decode. Applicable for "7280" switch model only, will assume "48bit" if unspecified. Note: "64bit" timestamps are DEPRECATED.
 *
 * <h3>Modes</h3>
 * \subpage sc_arista7150_ts_node "sc_arista_ts, switch_model=7150" | \copybrief sc_arista7150_ts_node
 *
 * \subpage sc_arista7280_64bit_ts_node "sc_arista_ts, switch_model=7280, ts_format=64bit" | \copybrief sc_arista7280_64bit_ts_node
 *
 * \subpage sc_arista7280_48bit_ts_node "sc_arista_ts, switch_model=7280, ts_format=48bit" | \copybrief sc_arista7280_48bit_ts_node
 */

/**
 * \nodestats{sc_arista_ts}
 *
 * \brief Node stats from sc_arista_ts node, stats exposed depend on the
 * value of the switch_model argument.
 *
 * <h3>Modes</h3>
 * \subpage sc_arista7150_ts_stats "sc_arista_ts, switch_model=7150" | \copybrief sc_arista7150_ts_stats
 *
 * \subpage sc_arista7280_64bit_ts_stats "sc_arista_ts, switch_model=7280, ts_format=64bit" | \copybrief sc_arista7280_64bit_ts_stats
 *
 * \subpage sc_arista7280_48bit_ts_stats "sc_arista_ts, switch_model=7280, ts_format=48bit" | \copybrief sc_arista7280_48bit_ts_stats
 */



/* \cond NODOC */


#include <sc_internal.h>
#include <sc_internal/builtin_nodes.h>

#include <errno.h>

static int arista_ts_init(struct sc_node* node, const struct sc_attr* attr,
                          const struct sc_node_factory* factory)
{
  static struct sc_node_type* nt;
  if( nt == NULL ) {
    sc_node_type_alloc(&nt, NULL, factory);
  }
  node->nd_type = nt;

  const char *switch_model;
  if( sc_node_init_get_arg_str(&switch_model, node, "switch_model", NULL) < 0 )
    return -1;

  const char *ts_format;
  if( sc_node_init_get_arg_str(&ts_format, node, "ts_format", NULL) < 0 )
    return -1;

  if( switch_model == NULL || !strcmp(switch_model, "7150") )
    /* Assume user wants arista 7150 if they do not specify protocol. */
    if ( ts_format == NULL )
      return sc_node_init_delegate(node, attr, &sc_arista7150_ts_sc_node_factory, NULL, -1);
    else
      return sc_node_set_error(node, EINVAL, "sc_arista_ts: ERROR: arg "
                               "'ts_format' is supported for 'switch_model'='7280 only'\n");

  else if( !strcmp(switch_model, "7280") )
    if( ts_format == NULL || !strcmp(ts_format, "48bit") )
      return sc_node_init_delegate(node, attr, &sc_arista7280_48bit_ts_sc_node_factory, NULL, -1);
    else if( !strcmp(ts_format, "64bit") )
      return sc_node_init_delegate(node, attr, &sc_arista7280_64bit_ts_sc_node_factory, NULL, -1);
    else
      return sc_node_set_error(node, EINVAL, "sc_arista_ts: ERROR: arg "
                               "'ts_format' unknown mode %s\n", ts_format);

  else
    return sc_node_set_error(node, EINVAL, "sc_arista_ts: ERROR: arg "
                             "'switch_model' unknown mode %s\n", switch_model);
  return -1;
}



const struct sc_node_factory sc_arista_ts_sc_node_factory = {
  .nf_node_api_ver   = SC_API_VER,
  .nf_name           = "sc_arista_ts",
  .nf_source_file    = __FILE__,
  .nf_init_fn        = arista_ts_init,
};
