#! /usr/bin/python2

# SPDX-License-Identifier: MIT
# X-SPDX-Copyright-Text: Copyright (C) 2022, Advanced Micro Devices, Inc.

#
# Regression test for bug60006: failure to parse size strings using
# 'MiB' style suffixes.

import os, sys
import solar_capture


def main():
    s = solar_capture.new_session()
    t = s.new_thread()
    n = t.new_node('sc_pool_forwarder', attr={'pool_size': '160MiB'})

if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print e
        sys.exit(1)
